[package]
name = "PSaaS"
version = "0.1.0"
authors = ["Andrew Gunnerson <andrew.gunnerson@us.ibm.com>"]
edition = "2018"

[profile.release]
opt-level = 3

[dependencies]
pretty_env_logger = "0.3.1"
tokio = { version = "0.2", features = ["macros"] }
warp = "0.2"
