[package]
name = "PSaaS"
version = "0.1.0"
authors = ["Andrew Gunnerson <andrew.gunnerson@us.ibm.com>"]
edition = "2018"

[dependencies]
rocket = "0.4"
rocket_contrib = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
